### ISSUE TITLE
Suggestion: Add approve changes grey

### ISSUE THREAD

**Issue by wdhdev** [Readme-Workflows/Readme-Icons#28]
Add an image for approved changes but in grey, since if the user isn't need for a review it will be grey not green.

Example:
![image](https://user-images.githubusercontent.com/87287585/195290086-8a904fc6-d0ca-4bbc-aa95-a1071494ea7e.png)

**Comment by Andre601** [comment]
Added it as part of [v1.1.4](https://github.com/Readme-Workflows/Readme-Icons/releases/tag/v1.1.4)

**Comment by wdhdev** [comment]
> Added it as part of [v1.1.4](https://github.com/Readme-Workflows/Readme-Icons/releases/tag/v1.1.4)

Wow, that was fast!
